services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Unplug


  backend:
    build:
      context: .
      target: builder
    restart: always
    ports:
      - 5000:5000
    links:
      - postgres:postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Unplug
    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - docker.env
